# Generated by Django 4.2.1 on 2024-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('street', models.CharField(max_length=75)),
                ('neighborhood', models.CharField(max_length=75)),
                ('number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('zip_code', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
