# Generated by Django 4.2.1 on 2024-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cnpj',
            field=models.CharField(default=1, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
