# Generated by Django 4.2.1 on 2024-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='super_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
