# Generated by Django 4.2.1 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_super_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='complement',
            field=models.CharField(default='a', max_length=75),
            preserve_default=False,
        ),
    ]
