# Generated by Django 4.2.1 on 2024-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='partner_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
