# Generated by Django 4.2.1 on 2024-03-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='complement',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
