# Generated by Django 4.2.1 on 2024-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_restaurant_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
