# Generated by Django 4.2.1 on 2024-03-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_alter_restaurant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
