# Generated by Django 4.2.1 on 2024-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
