# Generated by Django 4.2.1 on 2024-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type_of',
            field=models.CharField(blank=True, choices=[('H', 'House'), ('W', 'Work'), ('AN', 'Another')], max_length=3, null=True),
        ),
    ]
