# Generated by Django 4.2.1 on 2024-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('EP', 'Em produção'), ('ER', 'Em rota de entrega'), ('DE', 'Entregue'), ('CA', 'Cancelado')], default='AG', max_length=20),
        ),
    ]
