# Generated by Django 4.2.1 on 2024-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('TK', 'Irá retirar o pedido na loja'), ('EE', 'Irá ser entregue')], default='TK', max_length=20),
        ),
    ]
