# Generated by Django 4.2.1 on 2024-02-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_customuser_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cpf_cnpj',
        ),
    ]
