# Generated by Django 4.2.1 on 2024-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
