# Generated by Django 4.2.1 on 2024-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_is_google_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_google_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
