# Generated by Django 4.2.1 on 2024-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_email_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
