# Generated by Django 4.2.1 on 2024-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_id',
        ),
    ]
