# Generated by Django 4.2.1 on 2024-03-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expiration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
