# Generated by Django 4.2.1 on 2024-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_otp_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
