# Generated by Django 4.2.1 on 2024-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_otp_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed_in',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_confirmed_in',
            field=models.DateTimeField(default=None),
        ),
    ]
