# Generated by Django 4.2.1 on 2024-03-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_product_restaurant_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
