# Generated by Django 4.2.1 on 2024-03-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_product_restaurant_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_ads',
            field=models.BooleanField(default=False),
        ),
    ]
