# Generated by Django 4.2.1 on 2024-03-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_address_complement'),
        ('users', '0027_customuser_receive_ads'),
    ]

    operations = [
    ]
