# Generated by Django 4.2.1 on 2024-03-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_customuser_receive_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
