# Generated by Django 4.2.1 on 2024-03-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20240315_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
