# Generated by Django 4.2.1 on 2024-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_product_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/logos/%Y/%m/%d'),
        ),
    ]
