# Generated by Django 4.2.1 on 2024-03-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_category_alter_product_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
